### ISSUE TITLE
Optimize the tracking

### ISSUE THREAD

**Issue by AndresRamirez9912** [AndresRamirez9912/Web-Scrapper#20]
Optimize the tracking cron using concurrency to reduce the computing and optimize the function.
This task is completed when:
- [ ] All products are scraping when the cron is executed 
- [ ] There aren't any race condition that returns an error
- [ ] Use channels to share information
